apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod-always
  labels:
    name: alpine-pod
spec:
  # restartPolicy: Always
  containers:
  - name: alpine-pod
    image: alpine:3.14
    command:
      - "/bin/sh"
      - "-c"
      - |
        touch /tmp/file1
        sleep 10
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: alpine-pod-onfailure
#   labels:
#     name: alpine-pod-onfailure
# spec:
#   restartPolicy: OnFailure
#   containers:
#   - name: alpine-pod-onfailure
#     image: alpine:3.14
#     command:
#       - "bin/bas"
#       - "-c"
#       - "touch /tmp/t1"
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: alpine-pod-never
#   labels:
#     name: alpine-pod-never
# spec:
#   restartPolicy: Never
#   containers:
#   - name: alpine-pod-onfailure
#     image: alpine:3.14
#     command:
#       - "bin/bas"
#       - "-c"
#       - "touch /tmp/t1"
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80


