apiVersion: apps/v1
kind: Deployment

{{ $myVar := true }}
{{- if $myVar}}
string:
  {{"hi this is working"}}
{{- else}}
string:
  {{"this is not ture"}}
{{- end}}

{{ "We are learing" }} {{"HELM"}}
{{ .Values.somevalues.address | upper  | nindent 2 }}
{{ .Values.somevalues.addresscap | lower | nindent 4 }}
{{ .Values.somevalues.email | default "this is null" | upper | nindent 6  }}

{{- if .Values.value.test }}
something: {{ "this is true" }}
{{- else }}
something: {{ "this is else block" }}
{{- end }}

{{- with .Values.myteam.name }}
teams:
  {{- toYaml . | nindent }}
{{- end }}

metadata:
  name: {{ include "first-chart.fullname" . }}
  labels:
    {{- include "first-chart.labels" . | nindent 4 }}
    name: {{ .Values.createdby.name }}
    version: {{ .Chart.AppVersion }}
  
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "first-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "first-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "first-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
