apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-deployment
spec:
  selector:
    matchLabels:
      app: probe-deployment
  template:
    metadata:
      labels:
        app: probe-deployment
    spec:
      containers:
      - name: probe-deployment
        image: alpine:latest
        command:
            - "/bin/sh"
            - "-c"
            - |
              touch /tmp/healthcheck
              sleep 60
              rm -rf /tmp/healthcheck
              sleep 300
        startupProbe:
          exec:
            command:
              - cat
              - /tmp/healthcheck
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthcheck
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
