apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret
spec:
  selector:
    matchLabels:
      app: nginx-secret
  template:
    metadata:
      labels:
        app: nginx-secret
    spec:
      containers:
      - name: nginx-secret
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pass1
