apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret-mount
spec:
  selector:
    matchLabels:
      app: nginx-secret-mount
  template:
    metadata:
      labels:
        app: nginx-secret-mount
    spec:
      containers:
      - name: nginx-secret-mount
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-vol
          mountPath: "/tmp"
          readOnly: true
                
      volumes:
      - name: my-vol
        secret:
          secretName: pass1
