apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-volume-cm
spec:
  selector:
    matchLabels:
      app: nginx-volume-cm
  template:
    metadata:
      labels:
        app: nginx-volume-cm
    spec:
      containers:
      - name: nginx-volume-cm
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cm-vol
          mountPath: "/tmp"
          readOnly: true
      
      volumes:
      - name: cm-vol
        configMap:
          name: configmap1
